name: Publish Docker image

on:
  push:
    branches: master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image (rails api server)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-api-server/Dockerfile
          push: true
          tags: ghcr.io/madxcompany/base-api-server:latest
          